// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqLbYm7YMvAi6IJQiRX9HB0nCIhtbozUs',
    appId: '1:919826978203:web:0ef150549ed6363b1cfd3e',
    messagingSenderId: '919826978203',
    projectId: 'smart-home-81d77',
    authDomain: 'smart-home-81d77.firebaseapp.com',
    databaseURL: 'https://smart-home-81d77-default-rtdb.firebaseio.com',
    storageBucket: 'smart-home-81d77.firebasestorage.app',
    measurementId: 'G-XWV3KFCBRR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQATFcUPeqLvwBZ_SqRqt0HJSrIpGaUyE',
    appId: '1:919826978203:android:1e7ffff423fb27a31cfd3e',
    messagingSenderId: '919826978203',
    projectId: 'smart-home-81d77',
    databaseURL: 'https://smart-home-81d77-default-rtdb.firebaseio.com',
    storageBucket: 'smart-home-81d77.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjYkYdCXR8xfh-PjVYQiazVtLc-bDCuRI',
    appId: '1:919826978203:ios:8fa414a6ce0aaec01cfd3e',
    messagingSenderId: '919826978203',
    projectId: 'smart-home-81d77',
    databaseURL: 'https://smart-home-81d77-default-rtdb.firebaseio.com',
    storageBucket: 'smart-home-81d77.firebasestorage.app',
    iosBundleId: 'com.example.smarthome',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjYkYdCXR8xfh-PjVYQiazVtLc-bDCuRI',
    appId: '1:919826978203:ios:8fa414a6ce0aaec01cfd3e',
    messagingSenderId: '919826978203',
    projectId: 'smart-home-81d77',
    databaseURL: 'https://smart-home-81d77-default-rtdb.firebaseio.com',
    storageBucket: 'smart-home-81d77.firebasestorage.app',
    iosBundleId: 'com.example.smarthome',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqLbYm7YMvAi6IJQiRX9HB0nCIhtbozUs',
    appId: '1:919826978203:web:5f04edfebc1771ba1cfd3e',
    messagingSenderId: '919826978203',
    projectId: 'smart-home-81d77',
    authDomain: 'smart-home-81d77.firebaseapp.com',
    databaseURL: 'https://smart-home-81d77-default-rtdb.firebaseio.com',
    storageBucket: 'smart-home-81d77.firebasestorage.app',
    measurementId: 'G-LMMFSFX000',
  );
}
